### ISSUE TITLE
Remember to open domain always under certain proxy container

### ISSUE THREAD

**Issue by slrslr** [bekh6ex/firefox-container-proxy#22]
Hello,

i just added this extension to my Firefox beta on Windows 10 and i am unable to find option to define certain site/domain/subdomain to always open under proxy/container of my choice. I mean so it is remembered across Firefox restarts and i no longer need to assign the container/proxy to the same site again.

**Comment by bekh6ex** [comment]
Hi!
There is a Mozilla built extension [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) that does exactly that. It's well tested, has quite big user base, and works well with Container Proxy (this is exactly how I use it).

So, I think the action item here would be:
  * update extension description to target this use case.

**Comment by slrslr** [comment]
Thanks, i am aware that also Sidebery extension does this.
I was thinking this would be handy and important feature also for this addon.

**Comment by bekh6ex** [comment]
I would like to avoid adding this feature because it will increase the complexity of the extension and will require additional permissions. 
I use Firefox Multi-Account Containers for this use-case, rely on it on daily basis and didn't have a single issue with it so far.

If there is a strong argument to add it I'm open to it, but will close the issue for now.
