### ISSUE TITLE
Add proxy DNS option

### ISSUE THREAD

**Issue by ww-9** [bekh6ex/firefox-container-proxy#23]
There is no "Send DNS through proxy" option, this way there is a DNS leak. Please consider adding it asap.

**Comment by bekh6ex** [comment]
It is enabled by default for Socks 4 and 5.
Other types of proxies cannot do it. See [proxyDNS parameter in JavaScript API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/ProxyInfo).

**Comment by bekh6ex** [comment]
Code reference: https://github.com/bekh6ex/firefox-container-proxy/blob/master/src/store/Store.js#L38-L45

**Comment by nobodysu** [comment]
Should be mentioned in the interface then.

**Comment by ww-9** [comment]
> It is enabled by default for Socks 4 and 5.
May be it's enabled but it leaks, I see both my providers and proxy dns. You can verify this at any dns leak checker. It doesn't leak with foxyproxy but it leaks with this extension.

**Comment by bekh6ex** [comment]
@ww-9 I cannot reproduce it reliably. Can you describe how exactly do you test and which checker do you use?

When I do a clean test, I get no leak. Used many DNS leak checkers.

**Comment by bekh6ex** [comment]
Since when are you using Container Proxy?
Maybe there was a bug in the code some time ago and you have `proxyDNS: true` in the extension storage.

Can you try go to the proxy settings and save them again?

**Comment by bekh6ex** [comment]
@nobodysu The idea was to not bother users with technical details. 
Personally, I wouldn't care if there is a problem could have been present but solved.
Although, if problem exists and user needs to take an action to solve it, notification is a MUST.
(Hope you get my point 😄 )

Do you disagree?

BTW, can you also check if you have a DNS leak?

**Comment by bekh6ex** [comment]
Hm...
I get DNS leak on my Linux machine, but not on Mac.
FF version 75 on both.

**Comment by ww-9** [comment]
Finally I've found the cause. When uBlock Origin is enabled it leaks, when it's not - no leak.

**Comment by bekh6ex** [comment]
@ww-9 It is kind of true.
I also notice occasional DNS leak, but cannot reproduce it with clean install.

**Comment by bug-repport** [comment]
On Win I do not observe leaks, everything is correct!

**Comment by ww-9** [comment]
will there be a fix?

**Comment by bekh6ex** [comment]
Sorry didn't have time lately to get back to this issue due to some COVID related things going on.

Although, I forgot to share some findings that I have:

  1. Stil cannot reproduce the leak from a clean state, but figured out that it is not a simple bug in the code. Each time the request is made from the checker page in container proxy settings provided by the extension are corect (i.e. proxy DNS flag is set to `true`).
  2. Disabling uBlock doesn't help the leak. Sometimes, when the leak is already present disabling uBlock on the page will refresh it and the leak will disappear. (Didn't try to uninstall uBlock so far, might be still relevant).
  3. Sometimes, after cleaning cookies and local storage the leak disappears (but not always).
  4. Changing the proxy for leaking container might fix the leak as well. (tried this once only and it helped)

**NOTE:** Used https://dnsleak.com

@ww-9 If you can share some results of your experiments that would be really helpful, because my curent assumption that it's either related to some other extension or there might be some tricky/unobvious Firefox behaviour that I'm not aware of which makes approach of Continer Proxy not robust enough to protect against it. Or maybe there is a bug in Firefox...

**Comment by ww-9** [comment]
@bekh6ex I confirm that it is not an obvious bug, and it’s quite difficult to figure out a pattern, however my steps to reproduce:
1. Install uBlock and this extension
2. Pin 2 tabs in firefox (ex. youtube and amazon)
3. Restart the browser

When either there are no pinned tabs after the restart or uBlock is disabled there is no leak.

**Comment by bekh6ex** [comment]
Cannot reproduce it on macOS 10.15.4 (Firefox version 76.0.1).

@ww-9 Which OS and Firefox do you have?

Also, how do you open these tabs? In container with proxy set up or in the default one?

**Comment by ww-9** [comment]
Windows 10, the same Firefox version. These pinned tabs in the default one.

Have you tried https://browserleaks.com/dns ?

**Comment by bekh6ex** [comment]
I still cannot reproduce DNS leak from a clean state, but I get it from time to time (checked it several times while working during the day).

Thinking about the cause, there is a core problem with the approach:
Extensions consist of different types of scripts (e.g. background script, popup script) that are being executed in the default container. If they send requests they will inherit Firefox Container Proxy settings for default container which is probably be set to `Directly` (i.e. without proxying). 
3rd party extension can decide to extract some links to resources from the open page and "explore" them for whatever reason. In this case DNS leak might happen.

The only way to mitigate such issues is to set up proxy in Firefox settings so that EVERY request is proxied. Using extensions that let user to match proxy by domain name **has the same problem** because when proxy will get matched for `matching-domain.com` it won't get matched for `xxx.dns-leak-service.net` which might be added to the page in order to find out real user IP.

**Comment by sellibitze** [comment]
I have the same problem. A DNS leak test fails. Somehow, when I globally configure a SOCKS5 proxy, using Firefox' network settings with the "pass DNS requests through the proxy" option checked, I see no DNS leak. But when I'm on a containered tab with proxy settings controlled by this extension the DNS leak test fails and some of the requests are verifiably bypassing the SOCKS proxy. They hit my LAN's DNS server.

Is it possible that by "experimenting" with the "global settings" (including turning any proxy off) the DNS-over-SOCKS5 option is somehow disabled for the containered proxies as well?

**Comment by adamboutcher** [comment]
+1 request for tfhis feature.

**Comment by bekh6ex** [comment]
Thanks for the research!
Regarding PS: I see it as expected.
When you set up proxy in Firefox settings it is being used for all requests comming from Firefox (TCP, DNS, extensions, etc). When it is not set up, then the requests comming from the default container are not proxied and are sent directly, hence the leak.

**Comment by nobodysu** [comment]
Please bring up the setting to choose whether proxy DNS or not.
Not all socks have DNS-server capability.

**Comment by bekh6ex** [comment]
I expect to add this feature in the next days.

Regarding the DNS leak, I think it can be solved by using DNS over HTTPS.

**Comment by bekh6ex** [comment]
The feature is released. Update to 0.1.22

**Comment by xuhcc** [comment]
[cnameUncloak](https://github.com/gorhill/uBlock/wiki/Advanced-settings#cnameuncloak) setting is now located on a basic settings screen where it is called "Uncloak canonical names"
