### ISSUE TITLE
Some requests don't go through a proxy

### ISSUE THREAD

**Issue by Glide01** [bekh6ex/firefox-container-proxy#39]
I have a Tor container and have set up a Tor network for that container, but not all requests are going through the Tor network
Example:
I go to https://program-think.blogspot.com and there is a request for www.blogger.com that is sent directly from Firefox and does not go through the Tor network
<img width="999" alt="image" src="https://user-images.githubusercontent.com/24718328/124554540-aa4bee00-de68-11eb-8da4-24c4c5506b40.png">
But if I also set the Tor network for the Default container, there is no such problem.

**Comment by bekh6ex** [comment]
So, what I've seen before, it could be some add-on that for example parses the page and sends the request by itself. Almost each add-on have background script which runs in the default container (AFAIK it cannot be changed) and if this script issues a request it will be sent from the default container.
I've seen this issue already (see issue #23) with uBlock, sometimes requests leak, but I've never seen this issue with a clean FireFox installation without any add-ons except Container Proxy.

Saddly, this issue is not possible to fix in scope of Container Proxy.

Will close the issue for now. If you have more information, please reopen.
